-- ============================================================
-- Cuenta Corriente — Setup de tablas en Supabase
-- Ejecutar en Supabase SQL Editor (una sola vez)
-- ============================================================

-- Tabla: Proveedores (facturas a pagar)
-- Estado almacenado: PENDIENTE | SIN_FACTURA | PAGADA
-- Estado VENCIDA se calcula dinámicamente en la app
create table if not exists proveedores_cc (
    id                   bigint generated by default as identity primary key,
    proveedor            text not null,
    numero_factura       text,
    monto_local          numeric(14,2) default 0,
    moneda               text default 'GTQ',
    monto_usd            numeric(14,2) default 0,
    fecha_recibida       date,
    fecha_vencimiento    date,
    estado               text default 'PENDIENTE',
    tiene_factura        boolean default false,
    observaciones        text,
    fecha_pago           date,
    numero_transferencia text,
    comprobante_nombre   text,
    pais                 text default 'GUATEMALA',
    fecha_carga          timestamptz default now()
);

-- Tabla: Clientes (facturas a cobrar)
-- Estado almacenado: PENDIENTE | COBRADA
-- Estado VENCIDA se calcula dinámicamente en la app
create table if not exists clientes_cc (
    id                bigint generated by default as identity primary key,
    cliente           text not null,
    numero_factura    text,
    monto_local       numeric(14,2) default 0,
    moneda            text default 'GTQ',
    monto_usd         numeric(14,2) default 0,
    fecha_emision     date,
    fecha_vencimiento date,
    estado            text default 'PENDIENTE',
    observaciones     text,
    fecha_cobro       date,
    numero_referencia text,
    pais              text default 'GUATEMALA',
    fecha_carga       timestamptz default now()
);

-- Índices opcionales para mejorar performance
create index if not exists idx_proveedores_cc_estado    on proveedores_cc (estado);
create index if not exists idx_proveedores_cc_vencim    on proveedores_cc (fecha_vencimiento);
create index if not exists idx_clientes_cc_estado       on clientes_cc (estado);
create index if not exists idx_clientes_cc_vencim       on clientes_cc (fecha_vencimiento);
